export const REQUEST_BEGIN = '@@NEWS/REQUEST_BEGIN';
export const REQUEST_END = '@@NEWS/REQUEST_END';

export const SUCCESS_GET_NEWS = '@@NEWS/SUCCESS_GET_NEWS';
export const SUCCESS_GET_PARTICULAR_NEWS = '@@NEWS/SUCCESS_GET_PARTICULAR_NEWS';

export const SUCCESS_GET_ARTICLES = '@@NEWS/SUCCESS_GET_ARTICLES';
export const SUCCESS_GET_SORTED_ARTICLES = '@@NEWS/SUCCESS_GET_SORTED_ARTICLES';